### ISSUE TITLE
Not working on Windows 7 (x64,x86)

### ISSUE THREAD

**Issue by antimYT** [YatoDev/Yato.DirectXOverlay#7]
[Screenshot](https://imgur.com/a/chPL8)

**Comment by antimYT** [comment]
[Screenshot 2](https://imgur.com/a/5zD6t)

**Comment by antimYT** [comment]
Solution:
Open 'Direct2DRederer.cs' and replace **R8G8B8A8_UNorm** to **B8G8R8A8_UNorm** (line: 153)

**Comment by YatoDev** [comment]
i'll add a check for this

**Comment by YatoDev** [comment]
i've fixed the issue. Maybe you know a way to determine the supported features with sharpdx to always choose the right one
