### ISSUE TITLE
Overlay crash /stop?

### ISSUE THREAD

**Issue by lguilhermee** [YatoDev/Yato.DirectXOverlay#8]
I have tried it in a few games, and it seems that the overlay crash after sometime in game. The last 'overlay' that was draw its keeped on screen. I wish i could post any erros here, but on visual studios shows no erros, and even when i try to attach a debugger point on it, it nevers hits. Its seems like the loop inside of it its 'dead' or i don't know.

**Comment by YatoDev** [comment]
Try to reproduce the error in a little console app.
And please use "Debug" build configuration to debug your project.

No one can Help you with the given informations
