### ISSUE TITLE
variables not beeing set

### ISSUE THREAD

**Issue by LeagueRaINi** [YatoDev/Yato.DirectXOverlay#9]
this lib seems to get the target window size automatically (OverlayCreationOptions) even if u dont specify x, y, height & width which is pretty cool cause then i dont have to make extra calls myself to get the window rect which are useless anyway cause the window size can change aswell as the position but.....
x, y, height, width & targetwindowhandle are never set when i try to call them with the Direct2DRenderer (gfx from ur example) is this intended?

kinda sucks to make extra calls in the drawing loop to get them

**Comment by YatoDev** [comment]
What exactly do you mean?

If you mean the DirectXRenderer then x and y (left, top) always need to be 0 because they are relative to the windows client area

**Comment by YatoDev** [comment]
If you have time, link the code file and line so i can review it 👍

**Comment by LeagueRaINi** [comment]
![Preview](https://i.imgur.com/bS2nPhE.png)
https://ghostbin.com/paste/z2o3j

**Comment by YatoDev** [comment]
done
